# Generated by Django 5.2 on 2025-04-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_utilisateur_options_alter_utilisateur_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'Pending'), ('accepte', 'Accepted'), ('rejete', 'Rejected')], default='en_attente', max_length=20),
        ),
    ]
