# Generated by Django 5.2 on 2025-04-19 14:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_utilisateur_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrat',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='contrats/'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
