# Generated by Django 5.2 on 2025-04-22 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_evaluation_category_evaluation_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinpaie',
            name='status_pyment',
            field=models.CharField(default='not paid', max_length=50),
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('motif', models.TextField()),
                ('justifiee', models.BooleanField(default=False)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employe')),
            ],
        ),
    ]
