# Generated by Django 5.2 on 2025-04-22 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_bulletinpaie_status_pyment_absence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='mot_de_passe',
        ),
    ]
