# Generated by Django 5.2 on 2025-04-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_utilisateur_mot_de_passe'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='mot_de_passe',
            field=models.CharField(default=1234, max_length=255),
            preserve_default=False,
        ),
    ]
